from jie import generate_open_triple

data1 = [
    {'主语': [{'end': 3,
               'probability': 0.8272656,
               'relations': {'宾语': [{'end': 20,
                                       'probability': 0.8503405,
                                       'start': 12,
                                       'text': '2018年18%'}]},
               'start': 0,
               'text': '湖北省'}],
     '宾语': [{'end': 20,
               'probability': 0.98740137,
               'relations': {'关系': [{'end': 12,
                                       'probability': 0.9342915,
                                       'start': 10,
                                       'text': '超过'}]},
               'start': 12,
               'text': '2018年18%'}]}]

data2 = [
    {'主语': [
        {'end': 4,
         'probability': 0.9969324,
         'relations': {'宾语': [{'end': 30,
                                 'probability': 0.9984451,
                                 'start': 28,
                                 'text': '仓储'},
                                {'end': 36,
                                 'probability': 0.9970957,
                                 'start': 34,
                                 'text': '配送'},
                                {'end': 33,
                                 'probability': 0.9963066,
                                 'start': 31,
                                 'text': '分拨'},
                                {'end': 57,
                                 'probability': 0.9976372,
                                 'start': 54,
                                 'text': '价值链'},
                                {'end': 51,
                                 'probability': 0.9983989,
                                 'start': 48,
                                 'text': '产业链'},
                                {'end': 27,
                                 'probability': 0.9982898,
                                 'start': 25,
                                 'text': '运输'},
                                {'end': 39,
                                 'probability': 0.98884445,
                                 'start': 37,
                                 'text': '信息'},
                                {'end': 63,
                                 'probability': 0.99845,
                                 'start': 60,
                                 'text': '供应链'}]},
         'start': 2,
         'text': '物流'}],
        '宾语': [{'end': 57,
                  'probability': 0.9983546,
                  'relations': {'关系': [{'end': 54,
                                          'probability': 0.77039284,
                                          'start': 52,
                                          'text': '提升'}]},
                  'start': 54,
                  'text': '价值链'},
                 {'end': 39,
                  'probability': 0.9951989,
                  'relations': {'关系': [{'end': 25,
                                          'probability': 0.974124,
                                          'start': 23,
                                          'text': '融合'}]},
                  'start': 37,
                  'text': '信息'},
                 {'end': 36,
                  'probability': 0.998539,
                  'relations': {'关系': [{'end': 25,
                                          'probability': 0.9790066,
                                          'start': 23,
                                          'text': '融合'}]},
                  'start': 34,
                  'text': '配送'},
                 {'end': 63,
                  'probability': 0.99898607,
                  'relations': {'关系': [{'end': 60,
                                          'probability': 0.85423905,
                                          'start': 58,
                                          'text': '打造'}]},
                  'start': 60,
                  'text': '供应链'},
                 {'end': 33,
                  'probability': 0.99812037,
                  'relations': {'关系': [{'end': 25,
                                          'probability': 0.9842436,
                                          'start': 23,
                                          'text': '融合'}]},
                  'start': 31,
                  'text': '分拨'},
                 {'end': 27,
                  'probability': 0.9983585,
                  'relations': {'关系': [{'end': 25,
                                          'probability': 0.9579993,
                                          'start': 23,
                                          'text': '融合'}]},
                  'start': 25,
                  'text': '运输'},
                 {'end': 51,
                  'probability': 0.99873096,
                  'relations': {'关系': [{'end': 48,
                                          'probability': 0.9034736,
                                          'start': 46,
                                          'text': '延伸'}]},
                  'start': 48,
                  'text': '产业链'},
                 {'end': 30,
                  'probability': 0.9988764,
                  'relations': {'关系': [{'end': 25,
                                          'probability': 0.9572844,
                                          'start': 23,
                                          'text': '融合'}]},
                  'start': 28,
                  'text': '仓储'}]}]
